- name: Check for Xcode Command Line Tools
  stat:
    path: /Library/Developer/CommandLineTools
  register: xcode_cl_tools
  tags:
    - macos
    - xcode
    - homebrew

- name: Install command line tools
  when: not xcode_cl_tools.stat.exists
  block:
    - name: Create hidden install file
      file:
        path: /private/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
        state: touch
      tags:
        - macos
        - xcode
        - homebrew

    - name: List updates
      command: softwareupdate -l
      register: updates
      changed_when: no
      tags:
        - macos
        - xcode
        - homebrew

    - name: Install Xcode Command Line Tools
      command: softwareupdate --install "{{ package_name }}"
      args:
        creates: /Library/Developer/CommandLineTools
      vars:
        package_name: "{{ updates.stdout | regex_search('Command Line Tools for Xcode-.*', multiline=True) }}"
      tags:
        - macos
        - xcode
        - homebrew

  always:
    - name: Remove hidden install file
      file:
        path: /private/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
        state: absent
      tags:
        - guest_devtools

- name: Install Homebrew
  shell: 'echo "\r" | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  args:
    creates: "/usr/local/bin/brew"
  become: no
  tags:
    - macos
    - homebrew


- name: Install Homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps | default([]) }}"
  become: no
  tags:
    - macos
    - homebrew
    - packages
    - cask

- name: Install Homebrew packages
  homebrew:
    update_homebrew: yes
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  become: no
  loop: "{{ homebrew_packages }}"
  ignore_errors: yes
  tags:
    - macos
    - homebrew
    - packages

- name: Install Homebrew Cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_cask_apps }}"
  ignore_errors: yes
  become: no
  tags:
    - macos
    - homebrew
    - packages
    - cask
